"""empty message

Revision ID: 2c956079ad07
Revises: eb2e00358198
Create Date: 2020-08-26 21:06:24.684183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c956079ad07'
down_revision = 'eb2e00358198'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('is_planting', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'is_planting')
    ### end Alembic commands ###
