"""empty message

Revision ID: 55e2bf07d7e4
Revises: 7156e2fbcabe
Create Date: 2018-07-19 20:01:49.067230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e2bf07d7e4'
down_revision = '7156e2fbcabe'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'created')
    ### end Alembic commands ###
