"""empty message

Revision ID: 7156e2fbcabe
Revises: 
Create Date: 2018-07-19 19:49:21.638395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7156e2fbcabe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growers',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fields',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=250), nullable=True),
    sa.Column('grower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grower_id'], ['growers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fields')
    op.drop_table('growers')
    ### end Alembic commands ###
