"""empty message

Revision ID: 7fa7267eed8c
Revises: b5432adf2410
Create Date: 2018-09-17 18:22:02.122521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa7267eed8c'
down_revision = 'b5432adf2410'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('applied_acres', sa.Float(precision=10), nullable=True))
    op.add_column('fields', sa.Column('harvest_acres', sa.Float(precision=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'harvest_acres')
    op.drop_column('fields', 'applied_acres')
    ### end Alembic commands ###
