"""empty message

Revision ID: b5432adf2410
Revises: 2b4fe01749af
Create Date: 2018-08-27 20:31:31.016604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5432adf2410'
down_revision = '2b4fe01749af'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('is_visible', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'is_visible')
    ### end Alembic commands ###
