"""empty message

Revision ID: bd7caf6f9cf4
Revises: 0f781cb2e3f8
Create Date: 2019-02-01 22:08:43.007448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7caf6f9cf4'
down_revision = '0f781cb2e3f8'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('order_id', sa.String(length=50), nullable=True))
    op.add_column('fields', sa.Column('updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'updated')
    op.drop_column('fields', 'order_id')
    ### end Alembic commands ###
