"""empty message

Revision ID: c253d5398d47
Revises: 2b8622f90e52
Create Date: 2018-07-27 18:12:33.007964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c253d5398d47'
down_revision = '2b8622f90e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('yield_data', sa.Float(), nullable=True),
    sa.Column('app_data', sa.Float(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('growers', sa.Column('division', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('growers', 'division')
    op.drop_table('data')
    # ### end Alembic commands ###
