"""empty message

Revision ID: eb2e00358198
Revises: bd7caf6f9cf4
Create Date: 2019-09-09 20:25:37.308273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb2e00358198'
down_revision = 'bd7caf6f9cf4'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('applied_map_img', sa.String(length=250), nullable=True))
    op.add_column('fields', sa.Column('field_centroid', sa.String(length=100), nullable=True))
    op.drop_column('fields', 'order_id')
    op.drop_column('fields', 'job_status')
    op.drop_column('fields', 'updated')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('updated', mysql.DATETIME(), nullable=True))
    op.add_column('fields', sa.Column('job_status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('fields', sa.Column('order_id', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('fields', 'field_centroid')
    op.drop_column('fields', 'applied_map_img')
    ### end Alembic commands ###
